# Generated by Django 5.0.2 on 2024-04-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=400)),
                ('body', models.TextField()),
                ('link', models.CharField(max_length=500)),
                ('likeCount', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('publishedDate', models.DateField()),
            ],
        ),
    ]
